[tool.mypy]
python_version = "3.10"
# disallow_any_generics = true
disallow_untyped_defs = true
disallow_untyped_calls = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true

[tool.black]
line-length = 90
target-version = ['py310']
