[tool.black]
line-length = 90
target-version = ['py312']

[tool.linpgtoolbox.options]
smart_auto_module_combine = "all_in_one"

[tool.mypy]
disallow_untyped_calls = true
# disallow_any_generics = true
disallow_untyped_defs = true
python_version = "3.12"
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true

[tool.tomlsort]
all = true
in_place = true
spaces_indent_inline_array = 4
